### ISSUE TITLE
data is not defined

### ISSUE THREAD

**Issue by sunnybear** [rileypsmith/sklearn-som#2]
Occasionally you use data instead of X in fit method. need to be fixed.
n_samples = data.shape[0]
->
n_samples = X.shape[0]

input = data[idx]
->
input = X[idx]

**Comment by rileypsmith** [comment]
Hi thank you for pointing this out. The fix has been merged into the master, so if you pulled the code from GitHub you may simply do a `git pull` and will have the fix. If you installed sklearn-som from PyPi please run `pip install sklearn-som==1.0.1` and the issue should be resolved.

I am marking this as closed for now. If the issue persists please don't hesitate to respond.
