### ISSUE TITLE
SOM Results in different clustering

### ISSUE THREAD

**Issue by GsGithub17** [rileypsmith/sklearn-som#6]
Hi 

Every time I rerun, SOM results in a different clustering result. I tried to fix this using seeding but I wasn't successful. 

Please could you suggest on how to fix this?

Thanks!

**Comment by rileypsmith** [comment]
This is noted. I have been meaning to add better support for reproducible results so I will add this in an update which I will put out this afternoon. I will comment here and close this issue once the update is available.

**Comment by GsGithub17** [comment]
Thank you so much for your immediate attention to this!

I found it such a nice tool. Looking forward to the updated version.

Best,

Gemechis
------------------------------------------
Gemechis Degaga (Ph.D.)
Postdoctoral Research Associate
Michigan Technological University
Department of Physics
1400 Townsend DR--49931
Houghton Michigan
USA
Tel: +1 906 281 8149

**Comment by rileypsmith** [comment]
Gemechis, no problem. I have released a new version, sklearn-som version `1.1.0`. It adds support for reproducible results with a new parameter, `random_state`, passed to the `SOM` class during initialization. 

The docs may not be updated yet but I will have them updated tomorrow. Marking this as closed but please let me know if you have any issues with the new functionality.

**Comment by GsGithub17** [comment]
That is great news!

I'll test it and let you know.

Thank you,

Gemechis
------------------------------------------
Gemechis Degaga (Ph.D.)
Postdoctoral Research Associate
Michigan Technological University
Department of Physics
1400 Townsend DR--49931
Houghton Michigan
USA
Tel: +1 906 281 8149
